// <auto-generated />
using System;
using Files.Implementation;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Files.Implementation.Migrations
{
    [DbContext(typeof(FilesDbContext))]
    [Migration("20260807214321_InitialFiles")]
    partial class InitialFiles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("files")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Files.Implementation.AttachmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("CampId")
                        .HasColumnType("uuid")
                        .HasColumnName("camp_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset?>("PurgeAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("QuotaScope")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BlobName")
                        .IsUnique();

                    b.HasIndex("State", "PurgeAt");

                    b.HasIndex("OrganizationId", "CampId", "QuotaScope", "State");

                    b.HasIndex("OrganizationId", "CampId", "OwnerType", "OwnerId", "State");

                    b.ToTable("attachments", "files", t =>
                        {
                            t.HasCheckConstraint("CK_attachments_lifecycle", "(\"State\" IN ('PendingUpload', 'Available') AND \"DeletedAt\" IS NULL AND \"PurgeAt\" IS NULL) OR (\"State\" = 'Deleted' AND \"DeletedAt\" IS NOT NULL AND \"PurgeAt\" > \"DeletedAt\")");

                            t.HasCheckConstraint("CK_attachments_owner_scope", "(\"OwnerType\" = 'Recipe' AND camp_id IS NULL AND \"QuotaScope\" = 'OrganizationRecipeLibrary') OR (\"OwnerType\" <> 'Recipe' AND camp_id IS NOT NULL AND \"QuotaScope\" = 'Camp')");

                            t.HasCheckConstraint("CK_attachments_size", "\"SizeBytes\" > 0 AND \"SizeBytes\" <= 10485760");
                        });
                });

            modelBuilder.Entity("Files.Implementation.AttachmentReadGrantEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<Guid>("AttachmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("attachment_id");

                    b.Property<Guid?>("CampId")
                        .HasColumnType("uuid")
                        .HasColumnName("camp_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("ActorId", "ExpiresAt", "UsedAt");

                    b.ToTable("read_grants", "files", t =>
                        {
                            t.HasCheckConstraint("CK_read_grants_expiry", "\"ExpiresAt\" > \"CreatedAt\" AND \"ExpiresAt\" <= \"CreatedAt\" + interval '60 seconds'");

                            t.HasCheckConstraint("CK_read_grants_hash", "octet_length(\"TokenHash\") = 32");
                        });
                });

            modelBuilder.Entity("Files.Implementation.AttachmentReadGrantEntity", b =>
                {
                    b.HasOne("Files.Implementation.AttachmentEntity", null)
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
