<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Testing" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/FreizeitCockpit.AppHost/FreizeitCockpit.AppHost.csproj" />
  </ItemGroup>
</Project>
