<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/FreizeitCockpit.Web/FreizeitCockpit.Web.csproj" />
    <ProjectReference Include="../FreizeitCockpit.TestSupport/FreizeitCockpit.TestSupport.csproj" />
  </ItemGroup>
</Project>
