// <auto-generated />
using System;
using Camps.Implementation;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Camps.Implementation.Migrations
{
    [DbContext(typeof(CampsDbContext))]
    partial class CampsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("camps")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Camps.Implementation.CampEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DefaultPortions")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateOnly>("EndsOn")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Slug")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "Status", "StartsOn");

                    b.ToTable("camps", "camps", t =>
                        {
                            t.HasCheckConstraint("CK_camps_dates", "\"EndsOn\" >= \"StartsOn\"");

                            t.HasCheckConstraint("CK_camps_default_portions", "\"DefaultPortions\" > 0");

                            t.HasCheckConstraint("CK_camps_version", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("Camps.Implementation.ScheduleEntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Audience")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("CampId")
                        .HasColumnType("uuid")
                        .HasColumnName("camp_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Description")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<DateOnly?>("EndDateExclusive")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAllDay")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "CampId", "StartDate");

                    b.HasIndex("OrganizationId", "CampId", "StartsAtUtc");

                    b.ToTable("schedule_entries", "camps", t =>
                        {
                            t.HasCheckConstraint("CK_schedule_entries_timing", "(\"IsAllDay\" AND \"StartsAtUtc\" IS NULL AND \"EndsAtUtc\" IS NULL AND \"StartDate\" IS NOT NULL AND \"EndDateExclusive\" > \"StartDate\") OR (NOT \"IsAllDay\" AND \"StartsAtUtc\" IS NOT NULL AND \"EndsAtUtc\" > \"StartsAtUtc\" AND \"StartDate\" IS NULL AND \"EndDateExclusive\" IS NULL)");

                            t.HasCheckConstraint("CK_schedule_entries_version", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("Camps.Implementation.ScheduleResponsibilityEntity", b =>
                {
                    b.Property<Guid>("ScheduleEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_entry_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("CampId")
                        .HasColumnType("uuid")
                        .HasColumnName("camp_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("ScheduleEntryId", "UserId");

                    b.HasIndex("OrganizationId", "CampId", "ScheduleEntryId");

                    b.HasIndex("OrganizationId", "CampId", "UserId");

                    b.ToTable("schedule_responsibilities", "camps");
                });

            modelBuilder.Entity("Camps.Implementation.ScheduleEntryEntity", b =>
                {
                    b.HasOne("Camps.Implementation.CampEntity", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "CampId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Camps.Implementation.ScheduleResponsibilityEntity", b =>
                {
                    b.HasOne("Camps.Implementation.ScheduleEntryEntity", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "CampId", "ScheduleEntryId")
                        .HasPrincipalKey("OrganizationId", "CampId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
