// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Spiritual.Implementation;

#nullable disable

namespace Spiritual.Implementation.Migrations
{
    [DbContext(typeof(SpiritualDbContext))]
    [Migration("20260807144508_InitialSpiritual")]
    partial class InitialSpiritual
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("spiritual")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Spiritual.Implementation.BibleSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Attribution")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("CampId")
                        .HasColumnType("uuid")
                        .HasColumnName("camp_id");

                    b.Property<Guid>("DevotionId")
                        .HasColumnType("uuid")
                        .HasColumnName("devotion_id");

                    b.Property<string>("License")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("RetrievedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TechnicalTranslationId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TextExcerpt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TranslationDisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "CampId", "DevotionId", "RetrievedAt");

                    b.ToTable("bible_snapshots", "spiritual");
                });

            modelBuilder.Entity("Spiritual.Implementation.DevotionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BibleReference")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("CampId")
                        .HasColumnType("uuid")
                        .HasColumnName("camp_id");

                    b.Property<string>("CoreMessage")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurrentBibleSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_bible_snapshot_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MarkdownContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaterialNotes")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.PrimitiveCollection<Guid[]>("ResponsibleUserIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<Guid?>("ScheduleEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_entry_id");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CurrentBibleSnapshotId");

                    b.HasIndex("OrganizationId", "CampId", "DeletedAt");

                    b.HasIndex("OrganizationId", "CampId", "ScheduleEntryId");

                    b.ToTable("devotions", "spiritual");
                });

            modelBuilder.Entity("Spiritual.Implementation.DevotionEntity", b =>
                {
                    b.HasOne("Spiritual.Implementation.BibleSnapshotEntity", null)
                        .WithMany()
                        .HasForeignKey("CurrentBibleSnapshotId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
