<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OpenApiGenerateDocuments>true</OpenApiGenerateDocuments>
    <OpenApiDocumentsDirectory>$(MSBuildProjectDirectory)/openapi</OpenApiDocumentsDirectory>
    <OpenApiGenerateDocumentsOptions>--document-name v1</OpenApiGenerateDocumentsOptions>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Camps/Camps.Contracts/Camps.Contracts.csproj" />
    <ProjectReference Include="../Camps/Camps.Implementation/Camps.Implementation.csproj" />
    <ProjectReference Include="../Catering/Catering.Contracts/Catering.Contracts.csproj" />
    <ProjectReference Include="../Catering/Catering.Implementation/Catering.Implementation.csproj" />
    <ProjectReference Include="../FreizeitCockpit.ServiceDefaults/FreizeitCockpit.ServiceDefaults.csproj" />
    <ProjectReference Include="../Identity/Identity.Contracts/Identity.Contracts.csproj" />
    <ProjectReference Include="../Identity/Identity.Implementation/Identity.Implementation.csproj" />
    <ProjectReference Include="../Knowledge/Knowledge.Contracts/Knowledge.Contracts.csproj" />
    <ProjectReference Include="../Knowledge/Knowledge.Implementation/Knowledge.Implementation.csproj" />
    <ProjectReference Include="../Logistics/Logistics.Contracts/Logistics.Contracts.csproj" />
    <ProjectReference Include="../Logistics/Logistics.Implementation/Logistics.Implementation.csproj" />
    <ProjectReference Include="../Files/Files.Contracts/Files.Contracts.csproj" />
    <ProjectReference Include="../Files/Files.Implementation/Files.Implementation.csproj" />
    <ProjectReference Include="../Spiritual/Spiritual.Contracts/Spiritual.Contracts.csproj" />
    <ProjectReference Include="../Spiritual/Spiritual.Implementation/Spiritual.Implementation.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.Extensions.ApiDescription.Server" PrivateAssets="all" />
    <PackageReference Include="Microsoft.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
