// <auto-generated />
using System;
using Logistics.Implementation;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Logistics.Implementation.Migrations
{
    [DbContext(typeof(LogisticsDbContext))]
    [Migration("20260809105537_AddShoppingListTrash")]
    partial class AddShoppingListTrash
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("logistics")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Logistics.Implementation.MaterialRequirementEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampId")
                        .HasColumnType("uuid")
                        .HasColumnName("camp_id");

                    b.Property<string>("CustomUnitName")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("ProcurementSource")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<DateTimeOffset?>("PurgeAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("QuantityUnit")
                        .HasColumnType("integer");

                    b.Property<decimal>("QuantityValue")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<Guid?>("ScheduleEntryId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "CampId", "PurgeAt");

                    b.HasIndex("OrganizationId", "CampId", "ScheduleEntryId");

                    b.HasIndex("OrganizationId", "CampId", "Status");

                    b.ToTable("material_requirements", "logistics", t =>
                        {
                            t.HasCheckConstraint("CK_material_custom_unit", "(\"QuantityUnit\" = 5 AND \"CustomUnitName\" IS NOT NULL) OR (\"QuantityUnit\" <> 5 AND \"CustomUnitName\" IS NULL)");

                            t.HasCheckConstraint("CK_material_quantity", "\"QuantityValue\" > 0");

                            t.HasCheckConstraint("CK_material_version", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("Logistics.Implementation.MaterialResponsibilityEntity", b =>
                {
                    b.Property<Guid>("MaterialRequirementId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_requirement_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("CampId")
                        .HasColumnType("uuid")
                        .HasColumnName("camp_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("MaterialRequirementId", "UserId");

                    b.HasIndex("OrganizationId", "CampId", "MaterialRequirementId");

                    b.HasIndex("OrganizationId", "CampId", "UserId");

                    b.ToTable("material_responsibilities", "logistics");
                });

            modelBuilder.Entity("Logistics.Implementation.ShoppingCheckEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<Guid>("CampId")
                        .HasColumnType("uuid")
                        .HasColumnName("camp_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<long>("ResultingItemVersion")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ShoppingItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("shopping_item_id");

                    b.Property<Guid>("ShoppingListId")
                        .HasColumnType("uuid")
                        .HasColumnName("shopping_list_id");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "CampId", "ShoppingItemId", "OccurredAt");

                    b.ToTable("shopping_check_events", "logistics", t =>
                        {
                            t.HasCheckConstraint("CK_shopping_check_event_version", "\"ResultingItemVersion\" > 1");
                        });
                });

            modelBuilder.Entity("Logistics.Implementation.ShoppingItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampId")
                        .HasColumnType("uuid")
                        .HasColumnName("camp_id");

                    b.Property<Guid?>("CateringMealId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CateringRecipeSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CateringSnapshotIngredientId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CateringSourceRecipeId")
                        .HasColumnType("uuid");

                    b.Property<int?>("CateringSourceRecipeVersionNumber")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CheckedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("checked_by_user_id");

                    b.Property<string>("CustomUnitName")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MaterialRequirementId")
                        .HasColumnType("uuid");

                    b.Property<long?>("MaterialRequirementVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<int>("QuantityUnit")
                        .HasColumnType("integer");

                    b.Property<decimal>("QuantityValue")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<Guid>("ShoppingListId")
                        .HasColumnType("uuid")
                        .HasColumnName("shopping_list_id");

                    b.Property<int>("SourceKind")
                        .HasColumnType("integer");

                    b.Property<string>("SourceLabel")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("Store")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "CampId", "ShoppingListId", "IsChecked");

                    b.ToTable("shopping_items", "logistics", t =>
                        {
                            t.HasCheckConstraint("CK_shopping_items_check_state", "(\"IsChecked\" AND \"checked_by_user_id\" IS NOT NULL AND \"CheckedAt\" IS NOT NULL) OR (NOT \"IsChecked\" AND \"checked_by_user_id\" IS NULL AND \"CheckedAt\" IS NULL)");

                            t.HasCheckConstraint("CK_shopping_items_custom_unit", "(\"QuantityUnit\" = 5 AND \"CustomUnitName\" IS NOT NULL) OR (\"QuantityUnit\" <> 5 AND \"CustomUnitName\" IS NULL)");

                            t.HasCheckConstraint("CK_shopping_items_quantity", "\"QuantityValue\" > 0");

                            t.HasCheckConstraint("CK_shopping_items_source", "(\"SourceKind\" = 0 AND \"CateringMealId\" IS NULL AND \"CateringRecipeSnapshotId\" IS NULL AND \"CateringSnapshotIngredientId\" IS NULL AND \"CateringSourceRecipeId\" IS NULL AND \"CateringSourceRecipeVersionNumber\" IS NULL AND \"MaterialRequirementId\" IS NULL AND \"MaterialRequirementVersion\" IS NULL) OR (\"SourceKind\" = 1 AND \"CateringMealId\" IS NOT NULL AND \"CateringRecipeSnapshotId\" IS NOT NULL AND \"CateringSnapshotIngredientId\" IS NOT NULL AND \"CateringSourceRecipeId\" IS NOT NULL AND \"CateringSourceRecipeVersionNumber\" > 0 AND \"MaterialRequirementId\" IS NULL AND \"MaterialRequirementVersion\" IS NULL) OR (\"SourceKind\" = 2 AND \"MaterialRequirementId\" IS NOT NULL AND \"MaterialRequirementVersion\" > 0 AND \"CateringMealId\" IS NULL AND \"CateringRecipeSnapshotId\" IS NULL AND \"CateringSnapshotIngredientId\" IS NULL AND \"CateringSourceRecipeId\" IS NULL AND \"CateringSourceRecipeVersionNumber\" IS NULL)");

                            t.HasCheckConstraint("CK_shopping_items_version", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("Logistics.Implementation.ShoppingItemResponsibilityEntity", b =>
                {
                    b.Property<Guid>("ShoppingItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("shopping_item_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("CampId")
                        .HasColumnType("uuid")
                        .HasColumnName("camp_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("ShoppingListId")
                        .HasColumnType("uuid")
                        .HasColumnName("shopping_list_id");

                    b.HasKey("ShoppingItemId", "UserId");

                    b.HasIndex("OrganizationId", "CampId", "UserId");

                    b.HasIndex("OrganizationId", "CampId", "ShoppingListId", "ShoppingItemId");

                    b.ToTable("shopping_item_responsibilities", "logistics");
                });

            modelBuilder.Entity("Logistics.Implementation.ShoppingListEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampId")
                        .HasColumnType("uuid")
                        .HasColumnName("camp_id");

                    b.Property<long>("ChangeSequence")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset?>("PurgeAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "CampId", "Name");

                    b.HasIndex("OrganizationId", "CampId", "PurgeAt");

                    b.ToTable("shopping_lists", "logistics", t =>
                        {
                            t.HasCheckConstraint("CK_shopping_lists_change_sequence", "\"ChangeSequence\" > 0");

                            t.HasCheckConstraint("CK_shopping_lists_version", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("Logistics.Implementation.MaterialResponsibilityEntity", b =>
                {
                    b.HasOne("Logistics.Implementation.MaterialRequirementEntity", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "CampId", "MaterialRequirementId")
                        .HasPrincipalKey("OrganizationId", "CampId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Logistics.Implementation.ShoppingItemEntity", b =>
                {
                    b.HasOne("Logistics.Implementation.ShoppingListEntity", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "CampId", "ShoppingListId")
                        .HasPrincipalKey("OrganizationId", "CampId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Logistics.Implementation.ShoppingItemResponsibilityEntity", b =>
                {
                    b.HasOne("Logistics.Implementation.ShoppingItemEntity", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "CampId", "ShoppingListId", "ShoppingItemId")
                        .HasPrincipalKey("OrganizationId", "CampId", "ShoppingListId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
