// <auto-generated />
using System;
using Knowledge.Implementation;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Knowledge.Implementation.Migrations
{
    [DbContext(typeof(KnowledgeDbContext))]
    partial class KnowledgeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("knowledge")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Knowledge.Implementation.NoteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampId")
                        .HasColumnType("uuid")
                        .HasColumnName("camp_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean");

                    b.Property<string>("Markdown")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("character varying(50000)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset?>("PurgeAfter")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset?>("TrashedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TrashedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("trashed_by");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("State", "PurgeAfter");

                    b.HasIndex("OrganizationId", "CampId", "State", "IsPinned", "UpdatedAt");

                    b.ToTable("notes", "knowledge");
                });

            modelBuilder.Entity("Knowledge.Implementation.NoteLinkEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampId")
                        .HasColumnType("uuid")
                        .HasColumnName("camp_id");

                    b.Property<Guid>("NoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("note_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetTitleSnapshot")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "CampId");

                    b.HasIndex("NoteId", "OrganizationId", "CampId");

                    b.HasIndex("NoteId", "TargetType", "TargetId")
                        .IsUnique();

                    b.ToTable("note_links", "knowledge");
                });

            modelBuilder.Entity("Knowledge.Implementation.NoteTagEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampId")
                        .HasColumnType("uuid")
                        .HasColumnName("camp_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("NoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("note_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("Id");

                    b.HasIndex("NoteId", "NormalizedName")
                        .IsUnique();

                    b.HasIndex("NoteId", "OrganizationId", "CampId");

                    b.HasIndex("OrganizationId", "CampId", "NormalizedName");

                    b.ToTable("note_tags", "knowledge");
                });

            modelBuilder.Entity("Knowledge.Implementation.NoteLinkEntity", b =>
                {
                    b.HasOne("Knowledge.Implementation.NoteEntity", null)
                        .WithMany("Links")
                        .HasForeignKey("NoteId", "OrganizationId", "CampId")
                        .HasPrincipalKey("Id", "OrganizationId", "CampId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Knowledge.Implementation.NoteTagEntity", b =>
                {
                    b.HasOne("Knowledge.Implementation.NoteEntity", null)
                        .WithMany("Tags")
                        .HasForeignKey("NoteId", "OrganizationId", "CampId")
                        .HasPrincipalKey("Id", "OrganizationId", "CampId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Knowledge.Implementation.NoteEntity", b =>
                {
                    b.Navigation("Links");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
