// <auto-generated />
using System;
using Catering.Implementation;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Catering.Implementation.Migrations
{
    [DbContext(typeof(CateringDbContext))]
    partial class CateringDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catering")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Catering.Implementation.IngredientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MergedIntoIngredientId")
                        .HasColumnType("uuid")
                        .HasColumnName("merged_into_ingredient_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("ingredients", "catering");
                });

            modelBuilder.Entity("Catering.Implementation.MealEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampId")
                        .HasColumnType("uuid")
                        .HasColumnName("camp_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<int?>("PortionOverride")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ScheduleEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_entry_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "CampId");

                    b.ToTable("meals", "catering");
                });

            modelBuilder.Entity("Catering.Implementation.RecipeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("recipes", "catering");
                });

            modelBuilder.Entity("Catering.Implementation.RecipeIngredientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("CountUnitName")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingredient_id");

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("RecipeVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_version_id");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("RecipeVersionId");

                    b.ToTable("recipe_ingredients", "catering");
                });

            modelBuilder.Entity("Catering.Implementation.RecipeSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AllergenNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("BasePortions")
                        .HasColumnType("integer");

                    b.Property<Guid>("CampId")
                        .HasColumnType("uuid")
                        .HasColumnName("camp_id");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.PrimitiveCollection<string[]>("DietaryTags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<string>("KitchenNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("MealId")
                        .HasColumnType("uuid")
                        .HasColumnName("meal_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Preparation")
                        .IsRequired()
                        .HasMaxLength(16000)
                        .HasColumnType("character varying(16000)");

                    b.Property<Guid>("SourceRecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_recipe_id");

                    b.Property<int>("SourceRecipeVersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MealId", "IsCurrent");

                    b.HasIndex("OrganizationId", "CampId");

                    b.ToTable("recipe_snapshots", "catering");
                });

            modelBuilder.Entity("Catering.Implementation.RecipeVersionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AllergenNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("BasePortions")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.PrimitiveCollection<string[]>("DietaryTags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("KitchenNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Preparation")
                        .IsRequired()
                        .HasMaxLength(16000)
                        .HasColumnType("character varying(16000)");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("RecipeId", "Number")
                        .IsUnique();

                    b.ToTable("recipe_versions", "catering");
                });

            modelBuilder.Entity("Catering.Implementation.SnapshotIngredientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<Guid>("CampId")
                        .HasColumnType("uuid")
                        .HasColumnName("camp_id");

                    b.Property<string>("CountUnitName")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingredient_id");

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("RecipeSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_snapshot_id");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("RecipeSnapshotId");

                    b.HasIndex("OrganizationId", "CampId");

                    b.ToTable("snapshot_ingredients", "catering");
                });

            modelBuilder.Entity("Catering.Implementation.RecipeIngredientEntity", b =>
                {
                    b.HasOne("Catering.Implementation.RecipeVersionEntity", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catering.Implementation.RecipeSnapshotEntity", b =>
                {
                    b.HasOne("Catering.Implementation.MealEntity", null)
                        .WithMany("RecipeSnapshots")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catering.Implementation.RecipeVersionEntity", b =>
                {
                    b.HasOne("Catering.Implementation.RecipeEntity", null)
                        .WithMany("Versions")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catering.Implementation.SnapshotIngredientEntity", b =>
                {
                    b.HasOne("Catering.Implementation.RecipeSnapshotEntity", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catering.Implementation.MealEntity", b =>
                {
                    b.Navigation("RecipeSnapshots");
                });

            modelBuilder.Entity("Catering.Implementation.RecipeEntity", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Catering.Implementation.RecipeSnapshotEntity", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("Catering.Implementation.RecipeVersionEntity", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
