<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Identity/Identity.Contracts/Identity.Contracts.csproj" />
    <ProjectReference Include="../../src/Spiritual/Spiritual.Contracts/Spiritual.Contracts.csproj" />
    <ProjectReference Include="../../src/Spiritual/Spiritual.Implementation/Spiritual.Implementation.csproj" />
  </ItemGroup>

</Project>
